spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
logging:
  level:
    org:
      hibernate:
        stat: debug